### ISSUE TITLE
Create a plan to fix our Javadoc warnings

### ISSUE THREAD

**Issue by zromano** [smartsheet/smartsheet-java-sdk#61]
Currently our Javadocs are lacking and we get a lot of warnings during builds about missing Javadoc information. We should come up with a plan on how to fix all of the missing Javadoc information over time.

Acceptance Criteria:
- Tasks created to update our Javadoc information and enforce that new MRs don't introduce Javadoc warnings.

**Comment by priyankalakhe** [comment]
The javadoc warnings are in the hundreds and the 300-odd ones I've seen so far are mostly in pojos.
As we move more pojos to lombok, its possible that we won't need to fix the javadoc warnings.
I say that because here's what a draft MR with javadoc will look like - https://github.com/smartsheet/smartsheet-java-sdk/pull/105/files
We can do this work but it all gets blown away once we lombok-ify the classes
So, based on team consensus, closing this ticket for now. 

See more discussion in https://smartsheet.slack.com/archives/C04LFRLSDHR/p1728670020703579?thread_ts=1722632912.916819&cid=C04LFRLSDHR
